/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.sml.ui.internal.SmlActivator;

public class SmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmlActivator.getInstance().getInjector("org.xtext.example.sml.Sml");
	}

}
