/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.validation;

import org.xtext.example.sml.validation.AbstractSmlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SmlValidator extends AbstractSmlValidator {
}
