/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SmlStandaloneSetup extends SmlStandaloneSetupGenerated {

	def static void doSetup() {
		new SmlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
