/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.sml.sml;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aggregate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.Aggregate#getR <em>R</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getAggregate()
 * @model
 * @generated
 */
public interface Aggregate extends Task
{
  /**
   * Returns the value of the '<em><b>R</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.sml.sml.Region}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' reference list.
   * @see org.xtext.example.sml.sml.SmlPackage#getAggregate_R()
   * @model
   * @generated
   */
  EList<Region> getR();

} // Aggregate
