/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.sml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Circle D</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.CircleD#getR <em>R</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getCircleD()
 * @model
 * @generated
 */
public interface CircleD extends Dimension
{
  /**
   * Returns the value of the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>R</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' attribute.
   * @see #setR(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getCircleD_R()
   * @model
   * @generated
   */
  String getR();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.CircleD#getR <em>R</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' attribute.
   * @see #getR()
   * @generated
   */
  void setR(String value);

} // CircleD
