/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.sml.sml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compound Indicator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.CompoundIndicator#getOc <em>Oc</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getCompoundIndicator()
 * @model
 * @generated
 */
public interface CompoundIndicator extends EObject
{
  /**
   * Returns the value of the '<em><b>Oc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oc</em>' containment reference.
   * @see #setOc(Occurence)
   * @see org.xtext.example.sml.sml.SmlPackage#getCompoundIndicator_Oc()
   * @model containment="true"
   * @generated
   */
  Occurence getOc();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.CompoundIndicator#getOc <em>Oc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Oc</em>' containment reference.
   * @see #getOc()
   * @generated
   */
  void setOc(Occurence value);

} // CompoundIndicator
