/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml.sml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.Condition#getR <em>R</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Condition#getN <em>N</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Condition#getNest <em>Nest</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends Scope
{
  /**
   * Returns the value of the '<em><b>R</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' reference.
   * @see #setR(Region)
   * @see org.xtext.example.sml.sml.SmlPackage#getCondition_R()
   * @model
   * @generated
   */
  Region getR();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Condition#getR <em>R</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' reference.
   * @see #getR()
   * @generated
   */
  void setR(Region value);

  /**
   * Returns the value of the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' attribute.
   * @see #setN(int)
   * @see org.xtext.example.sml.sml.SmlPackage#getCondition_N()
   * @model
   * @generated
   */
  int getN();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Condition#getN <em>N</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' attribute.
   * @see #getN()
   * @generated
   */
  void setN(int value);

  /**
   * Returns the value of the '<em><b>Nest</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nest</em>' reference.
   * @see #setNest(Region)
   * @see org.xtext.example.sml.sml.SmlPackage#getCondition_Nest()
   * @model
   * @generated
   */
  Region getNest();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Condition#getNest <em>Nest</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nest</em>' reference.
   * @see #getNest()
   * @generated
   */
  void setNest(Region value);

} // Condition
