/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml.sml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Coordinate3 D</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.Coordinate3D#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Coordinate3D#getY <em>Y</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Coordinate3D#getZ <em>Z</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getCoordinate3D()
 * @model
 * @generated
 */
public interface Coordinate3D extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getCoordinate3D_X()
   * @model
   * @generated
   */
  String getX();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Coordinate3D#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(String value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getCoordinate3D_Y()
   * @model
   * @generated
   */
  String getY();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Coordinate3D#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(String value);

  /**
   * Returns the value of the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Z</em>' attribute.
   * @see #setZ(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getCoordinate3D_Z()
   * @model
   * @generated
   */
  String getZ();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Coordinate3D#getZ <em>Z</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Z</em>' attribute.
   * @see #getZ()
   * @generated
   */
  void setZ(String value);

} // Coordinate3D
