/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.sml.sml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition1</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.Definition1#getReferencepoint <em>Referencepoint</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Definition1#getDimensions <em>Dimensions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getDefinition1()
 * @model
 * @generated
 */
public interface Definition1 extends RegionDefinition
{
  /**
   * Returns the value of the '<em><b>Referencepoint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Referencepoint</em>' containment reference.
   * @see #setReferencepoint(Position)
   * @see org.xtext.example.sml.sml.SmlPackage#getDefinition1_Referencepoint()
   * @model containment="true"
   * @generated
   */
  Position getReferencepoint();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Definition1#getReferencepoint <em>Referencepoint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Referencepoint</em>' containment reference.
   * @see #getReferencepoint()
   * @generated
   */
  void setReferencepoint(Position value);

  /**
   * Returns the value of the '<em><b>Dimensions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dimensions</em>' containment reference.
   * @see #setDimensions(Dimension)
   * @see org.xtext.example.sml.sml.SmlPackage#getDefinition1_Dimensions()
   * @model containment="true"
   * @generated
   */
  Dimension getDimensions();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Definition1#getDimensions <em>Dimensions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dimensions</em>' containment reference.
   * @see #getDimensions()
   * @generated
   */
  void setDimensions(Dimension value);

} // Definition1
