/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml.sml;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition Two</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.DefinitionTwo#getPoint <em>Point</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getDefinitionTwo()
 * @model
 * @generated
 */
public interface DefinitionTwo extends RegionDefinition
{
  /**
   * Returns the value of the '<em><b>Point</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.sml.sml.Position}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Point</em>' containment reference list.
   * @see org.xtext.example.sml.sml.SmlPackage#getDefinitionTwo_Point()
   * @model containment="true"
   * @generated
   */
  EList<Position> getPoint();

} // DefinitionTwo
