/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml.sml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dimension1</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.Dimension1#getR <em>R</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Dimension1#getM1 <em>M1</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Dimension1#getH <em>H</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Dimension1#getM2 <em>M2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getDimension1()
 * @model
 * @generated
 */
public interface Dimension1 extends Dimension
{
  /**
   * Returns the value of the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' attribute.
   * @see #setR(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getDimension1_R()
   * @model
   * @generated
   */
  String getR();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Dimension1#getR <em>R</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' attribute.
   * @see #getR()
   * @generated
   */
  void setR(String value);

  /**
   * Returns the value of the '<em><b>M1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>M1</em>' attribute.
   * @see #setM1(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getDimension1_M1()
   * @model
   * @generated
   */
  String getM1();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Dimension1#getM1 <em>M1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>M1</em>' attribute.
   * @see #getM1()
   * @generated
   */
  void setM1(String value);

  /**
   * Returns the value of the '<em><b>H</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>H</em>' attribute.
   * @see #setH(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getDimension1_H()
   * @model
   * @generated
   */
  String getH();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Dimension1#getH <em>H</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>H</em>' attribute.
   * @see #getH()
   * @generated
   */
  void setH(String value);

  /**
   * Returns the value of the '<em><b>M2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>M2</em>' attribute.
   * @see #setM2(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getDimension1_M2()
   * @model
   * @generated
   */
  String getM2();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Dimension1#getM2 <em>M2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>M2</em>' attribute.
   * @see #getM2()
   * @generated
   */
  void setM2(String value);

} // Dimension1
