/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml.sml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.Element#getOb <em>Ob</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Element#getD <em>D</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Element#getW <em>W</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Element#getSm <em>Sm</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Element#getIt <em>It</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
  /**
   * Returns the value of the '<em><b>Ob</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ob</em>' attribute.
   * @see #setOb(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getElement_Ob()
   * @model
   * @generated
   */
  String getOb();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Element#getOb <em>Ob</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ob</em>' attribute.
   * @see #getOb()
   * @generated
   */
  void setOb(String value);

  /**
   * Returns the value of the '<em><b>D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>D</em>' containment reference.
   * @see #setD(Dimension2)
   * @see org.xtext.example.sml.sml.SmlPackage#getElement_D()
   * @model containment="true"
   * @generated
   */
  Dimension2 getD();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Element#getD <em>D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D</em>' containment reference.
   * @see #getD()
   * @generated
   */
  void setD(Dimension2 value);

  /**
   * Returns the value of the '<em><b>W</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>W</em>' attribute.
   * @see #setW(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getElement_W()
   * @model
   * @generated
   */
  String getW();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Element#getW <em>W</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>W</em>' attribute.
   * @see #getW()
   * @generated
   */
  void setW(String value);

  /**
   * Returns the value of the '<em><b>Sm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sm</em>' attribute.
   * @see #setSm(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getElement_Sm()
   * @model
   * @generated
   */
  String getSm();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Element#getSm <em>Sm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sm</em>' attribute.
   * @see #getSm()
   * @generated
   */
  void setSm(String value);

  /**
   * Returns the value of the '<em><b>It</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>It</em>' attribute.
   * @see #setIt(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getElement_It()
   * @model
   * @generated
   */
  String getIt();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Element#getIt <em>It</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>It</em>' attribute.
   * @see #getIt()
   * @generated
   */
  void setIt(String value);

} // Element
