/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml.sml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getEnvironmentElements()
 * @model
 * @generated
 */
public interface EnvironmentElements extends EObject
{
} // EnvironmentElements
