/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.sml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getEnvironmentElement()
 * @model
 * @generated
 */
public interface EnvironmentElement extends EnvironmentElements
{
} // EnvironmentElement
