/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.sml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lowerbound</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getLowerbound()
 * @model
 * @generated
 */
public interface Lowerbound extends Range
{
} // Lowerbound
