/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.sml.sml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loweror Equalbound</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getLowerorEqualbound()
 * @model
 * @generated
 */
public interface LowerorEqualbound extends Range
{
} // LowerorEqualbound
