/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.sml.sml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mission Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.MissionSpecification#getM <em>M</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.MissionSpecification#getMt <em>Mt</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.MissionSpecification#getOb <em>Ob</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getMissionSpecification()
 * @model
 * @generated
 */
public interface MissionSpecification extends EObject
{
  /**
   * Returns the value of the '<em><b>M</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>M</em>' containment reference.
   * @see #setM(Mission)
   * @see org.xtext.example.sml.sml.SmlPackage#getMissionSpecification_M()
   * @model containment="true"
   * @generated
   */
  Mission getM();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.MissionSpecification#getM <em>M</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>M</em>' containment reference.
   * @see #getM()
   * @generated
   */
  void setM(Mission value);

  /**
   * Returns the value of the '<em><b>Mt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mt</em>' containment reference.
   * @see #setMt(MissionTime)
   * @see org.xtext.example.sml.sml.SmlPackage#getMissionSpecification_Mt()
   * @model containment="true"
   * @generated
   */
  MissionTime getMt();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.MissionSpecification#getMt <em>Mt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mt</em>' containment reference.
   * @see #getMt()
   * @generated
   */
  void setMt(MissionTime value);

  /**
   * Returns the value of the '<em><b>Ob</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ob</em>' containment reference.
   * @see #setOb(MissionObjective)
   * @see org.xtext.example.sml.sml.SmlPackage#getMissionSpecification_Ob()
   * @model containment="true"
   * @generated
   */
  MissionObjective getOb();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.MissionSpecification#getOb <em>Ob</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ob</em>' containment reference.
   * @see #getOb()
   * @generated
   */
  void setOb(MissionObjective value);

} // MissionSpecification
