/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.sml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.Model#getArenas <em>Arenas</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Model#getEnv <em>Env</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Model#getSw <em>Sw</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Model#getOb <em>Ob</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Arenas</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arenas</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arenas</em>' containment reference.
   * @see #setArenas(Arena)
   * @see org.xtext.example.sml.sml.SmlPackage#getModel_Arenas()
   * @model containment="true"
   * @generated
   */
  Arena getArenas();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Model#getArenas <em>Arenas</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arenas</em>' containment reference.
   * @see #getArenas()
   * @generated
   */
  void setArenas(Arena value);

  /**
   * Returns the value of the '<em><b>Env</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env</em>' containment reference.
   * @see #setEnv(Environment)
   * @see org.xtext.example.sml.sml.SmlPackage#getModel_Env()
   * @model containment="true"
   * @generated
   */
  Environment getEnv();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Model#getEnv <em>Env</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env</em>' containment reference.
   * @see #getEnv()
   * @generated
   */
  void setEnv(Environment value);

  /**
   * Returns the value of the '<em><b>Sw</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sw</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sw</em>' containment reference.
   * @see #setSw(Swarmconf)
   * @see org.xtext.example.sml.sml.SmlPackage#getModel_Sw()
   * @model containment="true"
   * @generated
   */
  Swarmconf getSw();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Model#getSw <em>Sw</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sw</em>' containment reference.
   * @see #getSw()
   * @generated
   */
  void setSw(Swarmconf value);

  /**
   * Returns the value of the '<em><b>Ob</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ob</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ob</em>' containment reference.
   * @see #setOb(MissionObjective)
   * @see org.xtext.example.sml.sml.SmlPackage#getModel_Ob()
   * @model containment="true"
   * @generated
   */
  MissionObjective getOb();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Model#getOb <em>Ob</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ob</em>' containment reference.
   * @see #getOb()
   * @generated
   */
  void setOb(MissionObjective value);

} // Model
