/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.sml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Occurence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.Occurence#getK <em>K</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Occurence#getC <em>C</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getOccurence()
 * @model
 * @generated
 */
public interface Occurence extends EObject
{
  /**
   * Returns the value of the '<em><b>K</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>K</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>K</em>' attribute.
   * @see #setK(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getOccurence_K()
   * @model
   * @generated
   */
  String getK();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Occurence#getK <em>K</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>K</em>' attribute.
   * @see #getK()
   * @generated
   */
  void setK(String value);

  /**
   * Returns the value of the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>C</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' containment reference.
   * @see #setC(Condition)
   * @see org.xtext.example.sml.sml.SmlPackage#getOccurence_C()
   * @model containment="true"
   * @generated
   */
  Condition getC();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Occurence#getC <em>C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' containment reference.
   * @see #getC()
   * @generated
   */
  void setC(Condition value);

} // Occurence
