/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.sml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Penatly</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getPenatly()
 * @model
 * @generated
 */
public interface Penatly extends Occurence
{
} // Penatly
