/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml.sml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Region</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.Region#getColors <em>Colors</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Region#getShape2d <em>Shape2d</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Region#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.Region#getRegion <em>Region</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getRegion()
 * @model
 * @generated
 */
public interface Region extends EnvironmentElement
{
  /**
   * Returns the value of the '<em><b>Colors</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colors</em>' attribute.
   * @see #setColors(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getRegion_Colors()
   * @model
   * @generated
   */
  String getColors();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Region#getColors <em>Colors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Colors</em>' attribute.
   * @see #getColors()
   * @generated
   */
  void setColors(String value);

  /**
   * Returns the value of the '<em><b>Shape2d</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shape2d</em>' attribute.
   * @see #setShape2d(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getRegion_Shape2d()
   * @model
   * @generated
   */
  String getShape2d();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Region#getShape2d <em>Shape2d</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shape2d</em>' attribute.
   * @see #getShape2d()
   * @generated
   */
  void setShape2d(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getRegion_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Region#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Region</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Region</em>' containment reference.
   * @see #setRegion(RegionDefinition)
   * @see org.xtext.example.sml.sml.SmlPackage#getRegion_Region()
   * @model containment="true"
   * @generated
   */
  RegionDefinition getRegion();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Region#getRegion <em>Region</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Region</em>' containment reference.
   * @see #getRegion()
   * @generated
   */
  void setRegion(RegionDefinition value);

} // Region
