/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml.sml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scope</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.Scope#getSp <em>Sp</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sml.sml.SmlPackage#getScope()
 * @model
 * @generated
 */
public interface Scope extends EObject
{
  /**
   * Returns the value of the '<em><b>Sp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sp</em>' attribute.
   * @see #setSp(String)
   * @see org.xtext.example.sml.sml.SmlPackage#getScope_Sp()
   * @model
   * @generated
   */
  String getSp();

  /**
   * Sets the value of the '{@link org.xtext.example.sml.sml.Scope#getSp <em>Sp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sp</em>' attribute.
   * @see #getSp()
   * @generated
   */
  void setSp(String value);

} // Scope
