/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.generator;

import com.google.common.base.Objects;
import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.IntegerRange;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.xtext.example.sml.sml.Arena;
import org.xtext.example.sml.sml.CircleD;
import org.xtext.example.sml.sml.Coordinate;
import org.xtext.example.sml.sml.Dimension;
import org.xtext.example.sml.sml.ElementDescription;
import org.xtext.example.sml.sml.Environment;
import org.xtext.example.sml.sml.EnvironmentElement;
import org.xtext.example.sml.sml.EnvironmentElements;
import org.xtext.example.sml.sml.Light;
import org.xtext.example.sml.sml.Model;
import org.xtext.example.sml.sml.Obstacle;
import org.xtext.example.sml.sml.Position;
import org.xtext.example.sml.sml.RectangleD;
import org.xtext.example.sml.sml.Region;
import org.xtext.example.sml.sml.Swarmconf;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class SmlGenerator extends AbstractGenerator {
  @Inject
  @Extension
  private IQualifiedNameProvider _iQualifiedNameProvider;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    final Model model = ((Model) _head);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!-- ********* -->");
    _builder.newLine();
    _builder.append("<!-- * Arena * -->");
    _builder.newLine();
    _builder.append("<!-- ********* -->\t");
    _builder.newLine();
    _builder.append("\t        ");
    {
      Arena _arenas = model.getArenas();
      boolean _tripleNotEquals = (_arenas != null);
      if (_tripleNotEquals) {
        CharSequence _compile = this.compile(model.getArenas());
        _builder.append(_compile, "\t        ");
        _builder.append(" ");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t      \t\t\t");
    {
      Swarmconf _sw = model.getSw();
      boolean _tripleNotEquals_1 = (_sw != null);
      if (_tripleNotEquals_1) {
        CharSequence _compile_1 = this.compile(model.getSw());
        _builder.append(_compile_1, "\t      \t\t\t");
        _builder.append(" ");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t      \t\t\t");
    {
      Environment _env = model.getEnv();
      boolean _tripleNotEquals_2 = (_env != null);
      if (_tripleNotEquals_2) {
        CharSequence _compile_2 = this.compile(model.getEnv());
        _builder.append(_compile_2, "\t      \t\t\t");
        _builder.append(" ");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t      \t\t  ");
    _builder.append("<!-- ******************* -->");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<!-- * Physics engines * -->");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<!-- ******************* -->");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<physics_engines>");
    _builder.newLine();
    _builder.append("\t      \t\t    ");
    _builder.append("<dynamics2d id=\"dyn2d\" />");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("</physics_engines>");
    _builder.newLine();
    _builder.append("\t      \t\t");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<!-- ********* -->");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<!-- * Media * -->");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<!-- ********* -->");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<media>");
    _builder.newLine();
    _builder.append("\t      \t\t    ");
    _builder.append("<led id=\"leds\" grid_size=\"1,1,1\"/>");
    _builder.newLine();
    _builder.append("\t      \t\t    ");
    _builder.append("<range_and_bearing id=\"ircom\"/>");
    _builder.newLine();
    _builder.append("\t      \t\t    ");
    _builder.append("<range_and_bearing id=\"rab\"/>");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("</media>");
    _builder.newLine();
    _builder.append("\t      \t\t");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<!-- ***************** -->");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<!-- * Visualization * -->");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<!-- ***************** -->");
    _builder.newLine();
    _builder.append("\t      \t\t  ");
    _builder.append("<visualization/>");
    _builder.newLine();
    _builder.append("\t      \t\t");
    _builder.newLine();
    _builder.append("\t      \t\t");
    _builder.append("</argos-configuration>");
    _builder.newLine();
    fsa.generateFile("setup.xml", _builder);
  }
  
  public CharSequence compile(final Arena A) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((A != null)) {
        _builder.append("<arena size=\"");
        CharSequence _compile = this.compile(A.getS().getDimensions());
        _builder.append(_compile);
        _builder.append("\" center=\"");
        CharSequence _compile_1 = this.compile(A.getS().getReferencepoint());
        _builder.append(_compile_1);
        _builder.append("\">");
        _builder.newLineIfNotEmpty();
        _builder.append("\t           ");
        CharSequence _compileWalls = this.compileWalls(Integer.valueOf(4));
        _builder.append(_compileWalls, "\t           ");
        _builder.append("</arena>");
      }
    }
    return _builder;
  }
  
  public CharSequence compile(final Region d) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((d != null)) {
        CharSequence _compile = this.compile(d.getDimensions());
        _builder.append(_compile);
      }
    }
    return _builder;
  }
  
  public CharSequence compile(final Environment en) {
    StringConcatenation _builder = new StringConcatenation();
    {
      EList<EnvironmentElements> _environment = en.getEnvironment();
      for(final EnvironmentElements e : _environment) {
        _builder.append(" ");
        _builder.newLineIfNotEmpty();
        {
          if ((e instanceof ElementDescription)) {
            CharSequence _compile = this.compile(((ElementDescription) e));
            _builder.append(_compile);
            _builder.newLineIfNotEmpty();
          } else {
            if ((e instanceof EnvironmentElement)) {
              CharSequence _compile_1 = this.compile(((EnvironmentElement) e));
              _builder.append(_compile_1);
            }
          }
        }
        _builder.newLineIfNotEmpty();
        _builder.append("\t       \t        ");
      }
    }
    return _builder;
  }
  
  public CharSequence compile(final Swarmconf sw) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(" ");
    _builder.append("<distribute>");
    _builder.newLine();
    _builder.append("\t             ");
    _builder.append("<position method=\"");
    String _dis = sw.getPr().getDis();
    _builder.append(_dis, "\t             ");
    _builder.append("\" ");
    {
      String _dis_1 = sw.getPr().getDis();
      boolean _equals = Objects.equal(_dis_1, "uniform");
      if (_equals) {
        _builder.append(" min=\"0,0,0\" max=\"");
        CharSequence _compile = this.compile(sw.getPr().getK());
        _builder.append(_compile, "\t             ");
        _builder.append("\" />");
      } else {
        String _dis_2 = sw.getPr().getDis();
        boolean _equals_1 = Objects.equal(_dis_2, "gaussian");
        if (_equals_1) {
          _builder.append(" mean=\"0,0,0\" std_dev=\"360,0,0\" />");
        }
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t             ");
    _builder.append("<orientation method=\"");
    String _dis_3 = sw.getPr().getDis();
    _builder.append(_dis_3, "\t             ");
    _builder.append("\" ");
    {
      String _dis_4 = sw.getPr().getDis();
      boolean _equals_2 = Objects.equal(_dis_4, "uniform");
      if (_equals_2) {
        _builder.append(" min=\"0,0,0\" max=\"");
        CharSequence _compile_1 = this.compile(sw.getPr().getK());
        _builder.append(_compile_1, "\t             ");
        _builder.append("\" />");
      } else {
        String _dis_5 = sw.getPr().getDis();
        boolean _equals_3 = Objects.equal(_dis_5, "gaussian");
        if (_equals_3) {
          _builder.append(" mean=\"0,0,0\" std_dev=\"360,0,0\" />");
        }
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t             ");
    _builder.append("<entity quantity=\"");
    int _n = sw.getX().getN();
    _builder.append(_n, "\t             ");
    _builder.append("\" max_trials=\"100\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t               ");
    _builder.append("<");
    String _r = sw.getR();
    _builder.append(_r, "\t               ");
    _builder.append(" id=\"");
    String _substring = sw.getR().toString().substring(0, 2);
    _builder.append(_substring, "\t               ");
    _builder.append("\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t                 ");
    _builder.append("<controller ");
    {
      String _r_1 = sw.getR();
      boolean _equals_4 = Objects.equal(_r_1, "foot-boot");
      if (_equals_4) {
        _builder.append(" config=\"fdc\"");
      } else {
        String _r_2 = sw.getR();
        boolean _equals_5 = Objects.equal(_r_2, "e-puck");
        if (_equals_5) {
          _builder.append(" config=\"automode\"");
        }
      }
    }
    _builder.append(" />");
    _builder.newLineIfNotEmpty();
    _builder.append("\t               ");
    _builder.append("</");
    String _r_3 = sw.getR();
    _builder.append(_r_3, "\t               ");
    _builder.append(" >");
    _builder.newLineIfNotEmpty();
    _builder.append("\t            ");
    _builder.append("</entity>");
    _builder.newLine();
    _builder.append("\t           ");
    _builder.append("</distribute>  ");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final Coordinate n) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((n != null)) {
        String _x = n.getX();
        _builder.append(_x);
        _builder.append(",");
        String _y = n.getY();
        _builder.append(_y);
      }
    }
    return _builder;
  }
  
  public CharSequence compileWalls(final Integer n) {
    StringConcatenation _builder = new StringConcatenation();
    {
      IntegerRange _upTo = new IntegerRange(0, (n).intValue());
      for(final Integer i : _upTo) {
        _builder.append("<box id=\"wall");
        _builder.append(n);
        _builder.append("\" size=\"2,0.1,0.5\" movable=\"false\">");
        _builder.newLineIfNotEmpty();
        _builder.append("\t            ");
        _builder.append("<body position=\"0,1,0\" orientation=\"0,0,0\" />");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t          ");
    _builder.append("</box>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final ElementDescription ed) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(" ");
    _builder.append("<distribute>");
    _builder.newLine();
    _builder.append("\t             ");
    _builder.append("<position method=\"");
    String _dis = ed.getR().getDis();
    _builder.append(_dis, "\t             ");
    _builder.append("\" ");
    {
      String _dis_1 = ed.getR().getDis();
      boolean _equals = Objects.equal(_dis_1, "uniform");
      if (_equals) {
        _builder.append(" min=\"0,0,0\" max=\"");
        CharSequence _compile = this.compile(ed.getR().getK());
        _builder.append(_compile, "\t             ");
        _builder.append("\" />");
      } else {
        String _dis_2 = ed.getR().getDis();
        boolean _equals_1 = Objects.equal(_dis_2, "gaussian");
        if (_equals_1) {
          _builder.append(" mean=\"0,0,0\" std_dev=\"360,0,0\" />");
        }
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t             ");
    _builder.append("<orientation method=\"");
    String _dis_3 = ed.getR().getDis();
    _builder.append(_dis_3, "\t             ");
    _builder.append("\" ");
    {
      String _dis_4 = ed.getR().getDis();
      boolean _equals_2 = Objects.equal(_dis_4, "uniform");
      if (_equals_2) {
        _builder.append(" min=\"0,0,0\" max=\"");
        CharSequence _compile_1 = this.compile(ed.getR().getK());
        _builder.append(_compile_1, "\t             ");
        _builder.append("\" />");
      } else {
        String _dis_5 = ed.getR().getDis();
        boolean _equals_3 = Objects.equal(_dis_5, "gaussian");
        if (_equals_3) {
          _builder.append(" mean=\"0,0,0\" std_dev=\"360,0,0\" />");
        }
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t             ");
    _builder.append("<entity quantity=\"");
    int _n = ed.getX().getN();
    _builder.append(_n, "\t             ");
    _builder.append("\" max_trials=\"100\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t                 ");
    _builder.append("<box id=\"b");
    double _random = Math.random();
    double _multiply = (_random * 100);
    _builder.append(_multiply, "\t                 ");
    _builder.append("\" size=\"");
    double _random_1 = Math.random();
    double _multiply_1 = (_random_1 * 49);
    double _plus = (_multiply_1 + 1);
    _builder.append(_plus, "\t                 ");
    _builder.append(",");
    double _random_2 = Math.random();
    double _multiply_2 = (_random_2 * 49);
    double _plus_1 = (_multiply_2 + 1);
    _builder.append(_plus_1, "\t                 ");
    _builder.append(",");
    double _random_3 = Math.random();
    double _multiply_3 = (_random_3 * 49);
    double _plus_2 = (_multiply_3 + 1);
    _builder.append(_plus_2, "\t                 ");
    _builder.append("\" movable=\"false\" />");
    _builder.newLineIfNotEmpty();
    _builder.append("\t            ");
    _builder.append("</entity>");
    _builder.newLine();
    _builder.append("\t           ");
    _builder.append("</distribute>  ");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final EnvironmentElement en) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((en instanceof Obstacle)) {
        _builder.newLineIfNotEmpty();
        CharSequence _compile = this.compile(((Obstacle) en));
        _builder.append(_compile);
        _builder.newLineIfNotEmpty();
      } else {
        if ((en instanceof org.xtext.example.sml.sml.Object)) {
          CharSequence _compile_1 = this.compile(((org.xtext.example.sml.sml.Object) en));
          _builder.append(_compile_1);
          _builder.newLineIfNotEmpty();
        } else {
          if ((en instanceof Light)) {
            CharSequence _compile_2 = this.compile(((Light) en));
            _builder.append(_compile_2);
            _builder.newLineIfNotEmpty();
            _builder.append("\t       \t        ");
          }
        }
      }
    }
    return _builder;
  }
  
  public CharSequence compile(final Obstacle ob) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<box id=\"wall");
    double _random = Math.random();
    double _multiply = (_random * 100);
    _builder.append(_multiply);
    _builder.append("\" size=\"");
    CharSequence _compile = this.compile(ob.getR().getDimensions());
    _builder.append(_compile);
    _builder.append("\" movable=\"false\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t            ");
    _builder.append("<body position=\"");
    CharSequence _compile_1 = this.compile(ob.getR().getReferencepoint());
    _builder.append(_compile_1, "\t            ");
    _builder.append("\" orientation=\"0,0,0\" />");
    _builder.newLineIfNotEmpty();
    _builder.append("\t          ");
    _builder.append("</box>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final org.xtext.example.sml.sml.Object ob) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<box id=\"wall");
    double _random = Math.random();
    double _multiply = (_random * 100);
    _builder.append(_multiply);
    _builder.append("\" size=\"");
    CharSequence _compile = this.compile(ob.getR().getDimensions());
    _builder.append(_compile);
    _builder.append("\" movable=\"true\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t            ");
    _builder.append("<body position=\"");
    CharSequence _compile_1 = this.compile(ob.getR().getReferencepoint());
    _builder.append(_compile_1, "\t            ");
    _builder.append("\" orientation=\"0,0,0\" />");
    _builder.newLineIfNotEmpty();
    _builder.append("\t          ");
    _builder.append("</box>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final Light l) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<light id=\"light");
    double _random = Math.random();
    double _multiply = (_random * 100);
    _builder.append(_multiply);
    _builder.append("\" position=\"");
    CharSequence _compile = this.compile(l.getP());
    _builder.append(_compile);
    _builder.append("\" orientation=\"0,0,0\" color=\"");
    String _c = l.getC();
    _builder.append(_c);
    _builder.append("\" intensity=\"0.0\" medium=\"leds\"/>");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence compile(final Dimension d) {
    CharSequence _xifexpression = null;
    if ((d instanceof RectangleD)) {
      _xifexpression = this.compile(((RectangleD) d));
    } else {
      CharSequence _xifexpression_1 = null;
      if ((d instanceof CircleD)) {
        _xifexpression_1 = this.compile(((CircleD) d));
      }
      _xifexpression = _xifexpression_1;
    }
    return _xifexpression;
  }
  
  public CharSequence compile(final Position pt) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((pt != null)) {
        CharSequence _compile = this.compile(pt.getPoint());
        _builder.append(_compile);
      }
    }
    return _builder;
  }
  
  public CharSequence compile(final RectangleD k) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((k != null)) {
        String _l = k.getL();
        _builder.append(_l);
        _builder.append(", ");
        String _w = k.getW();
        _builder.append(_w);
        _builder.append(", ");
        String _h = k.getH();
        _builder.append(_h);
      }
    }
    return _builder;
  }
  
  public CharSequence compile(final CircleD k) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((k != null)) {
        String _r = k.getR();
        _builder.append(_r);
        _builder.append(" ");
      }
    }
    return _builder;
  }
}
