/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.sml.SmlRuntimeModule;
import org.xtext.example.sml.SmlStandaloneSetup;
import org.xtext.example.sml.ide.SmlIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SmlIdeSetup extends SmlStandaloneSetup {
  @Override
  public Injector createInjector() {
    SmlRuntimeModule _smlRuntimeModule = new SmlRuntimeModule();
    SmlIdeModule _smlIdeModule = new SmlIdeModule();
    return Guice.createInjector(Modules2.mixin(_smlRuntimeModule, _smlIdeModule));
  }
}
