/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml;

import org.xtext.example.sml.AbstractSmlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmlRuntimeModule extends AbstractSmlRuntimeModule {
}
