/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.sml.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.sml.sml.AtomicIndicator;
import org.xtext.example.sml.sml.Occurence;
import org.xtext.example.sml.sml.SmlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atomic Indicator</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.impl.AtomicIndicatorImpl#getOc <em>Oc</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtomicIndicatorImpl extends MinimalEObjectImpl.Container implements AtomicIndicator
{
  /**
   * The cached value of the '{@link #getOc() <em>Oc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOc()
   * @generated
   * @ordered
   */
  protected Occurence oc;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtomicIndicatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmlPackage.Literals.ATOMIC_INDICATOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Occurence getOc()
  {
    return oc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOc(Occurence newOc, NotificationChain msgs)
  {
    Occurence oldOc = oc;
    oc = newOc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SmlPackage.ATOMIC_INDICATOR__OC, oldOc, newOc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOc(Occurence newOc)
  {
    if (newOc != oc)
    {
      NotificationChain msgs = null;
      if (oc != null)
        msgs = ((InternalEObject)oc).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SmlPackage.ATOMIC_INDICATOR__OC, null, msgs);
      if (newOc != null)
        msgs = ((InternalEObject)newOc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SmlPackage.ATOMIC_INDICATOR__OC, null, msgs);
      msgs = basicSetOc(newOc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmlPackage.ATOMIC_INDICATOR__OC, newOc, newOc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SmlPackage.ATOMIC_INDICATOR__OC:
        return basicSetOc(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmlPackage.ATOMIC_INDICATOR__OC:
        return getOc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmlPackage.ATOMIC_INDICATOR__OC:
        setOc((Occurence)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmlPackage.ATOMIC_INDICATOR__OC:
        setOc((Occurence)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmlPackage.ATOMIC_INDICATOR__OC:
        return oc != null;
    }
    return super.eIsSet(featureID);
  }

} //AtomicIndicatorImpl
