/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.sml.sml.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.sml.sml.Dimension2;
import org.xtext.example.sml.sml.Element;
import org.xtext.example.sml.sml.SmlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sml.sml.impl.ElementImpl#getOb <em>Ob</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.impl.ElementImpl#getD <em>D</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.impl.ElementImpl#getW <em>W</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.impl.ElementImpl#getSm <em>Sm</em>}</li>
 *   <li>{@link org.xtext.example.sml.sml.impl.ElementImpl#getIt <em>It</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ElementImpl extends MinimalEObjectImpl.Container implements Element
{
  /**
   * The default value of the '{@link #getOb() <em>Ob</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOb()
   * @generated
   * @ordered
   */
  protected static final String OB_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOb() <em>Ob</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOb()
   * @generated
   * @ordered
   */
  protected String ob = OB_EDEFAULT;

  /**
   * The cached value of the '{@link #getD() <em>D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getD()
   * @generated
   * @ordered
   */
  protected Dimension2 d;

  /**
   * The default value of the '{@link #getW() <em>W</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getW()
   * @generated
   * @ordered
   */
  protected static final String W_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getW() <em>W</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getW()
   * @generated
   * @ordered
   */
  protected String w = W_EDEFAULT;

  /**
   * The default value of the '{@link #getSm() <em>Sm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSm()
   * @generated
   * @ordered
   */
  protected static final String SM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSm() <em>Sm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSm()
   * @generated
   * @ordered
   */
  protected String sm = SM_EDEFAULT;

  /**
   * The default value of the '{@link #getIt() <em>It</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIt()
   * @generated
   * @ordered
   */
  protected static final String IT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIt() <em>It</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIt()
   * @generated
   * @ordered
   */
  protected String it = IT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmlPackage.Literals.ELEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOb()
  {
    return ob;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOb(String newOb)
  {
    String oldOb = ob;
    ob = newOb;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmlPackage.ELEMENT__OB, oldOb, ob));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dimension2 getD()
  {
    return d;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetD(Dimension2 newD, NotificationChain msgs)
  {
    Dimension2 oldD = d;
    d = newD;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SmlPackage.ELEMENT__D, oldD, newD);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setD(Dimension2 newD)
  {
    if (newD != d)
    {
      NotificationChain msgs = null;
      if (d != null)
        msgs = ((InternalEObject)d).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SmlPackage.ELEMENT__D, null, msgs);
      if (newD != null)
        msgs = ((InternalEObject)newD).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SmlPackage.ELEMENT__D, null, msgs);
      msgs = basicSetD(newD, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmlPackage.ELEMENT__D, newD, newD));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getW()
  {
    return w;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setW(String newW)
  {
    String oldW = w;
    w = newW;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmlPackage.ELEMENT__W, oldW, w));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSm()
  {
    return sm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSm(String newSm)
  {
    String oldSm = sm;
    sm = newSm;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmlPackage.ELEMENT__SM, oldSm, sm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getIt()
  {
    return it;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIt(String newIt)
  {
    String oldIt = it;
    it = newIt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmlPackage.ELEMENT__IT, oldIt, it));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SmlPackage.ELEMENT__D:
        return basicSetD(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmlPackage.ELEMENT__OB:
        return getOb();
      case SmlPackage.ELEMENT__D:
        return getD();
      case SmlPackage.ELEMENT__W:
        return getW();
      case SmlPackage.ELEMENT__SM:
        return getSm();
      case SmlPackage.ELEMENT__IT:
        return getIt();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmlPackage.ELEMENT__OB:
        setOb((String)newValue);
        return;
      case SmlPackage.ELEMENT__D:
        setD((Dimension2)newValue);
        return;
      case SmlPackage.ELEMENT__W:
        setW((String)newValue);
        return;
      case SmlPackage.ELEMENT__SM:
        setSm((String)newValue);
        return;
      case SmlPackage.ELEMENT__IT:
        setIt((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmlPackage.ELEMENT__OB:
        setOb(OB_EDEFAULT);
        return;
      case SmlPackage.ELEMENT__D:
        setD((Dimension2)null);
        return;
      case SmlPackage.ELEMENT__W:
        setW(W_EDEFAULT);
        return;
      case SmlPackage.ELEMENT__SM:
        setSm(SM_EDEFAULT);
        return;
      case SmlPackage.ELEMENT__IT:
        setIt(IT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmlPackage.ELEMENT__OB:
        return OB_EDEFAULT == null ? ob != null : !OB_EDEFAULT.equals(ob);
      case SmlPackage.ELEMENT__D:
        return d != null;
      case SmlPackage.ELEMENT__W:
        return W_EDEFAULT == null ? w != null : !W_EDEFAULT.equals(w);
      case SmlPackage.ELEMENT__SM:
        return SM_EDEFAULT == null ? sm != null : !SM_EDEFAULT.equals(sm);
      case SmlPackage.ELEMENT__IT:
        return IT_EDEFAULT == null ? it != null : !IT_EDEFAULT.equals(it);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ob: ");
    result.append(ob);
    result.append(", w: ");
    result.append(w);
    result.append(", sm: ");
    result.append(sm);
    result.append(", it: ");
    result.append(it);
    result.append(')');
    return result.toString();
  }

} //ElementImpl
