/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.sml.sml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.sml.sml.LowerorEqualbound;
import org.xtext.example.sml.sml.SmlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Loweror Equalbound</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LowerorEqualboundImpl extends RangeImpl implements LowerorEqualbound
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LowerorEqualboundImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmlPackage.Literals.LOWEROR_EQUALBOUND;
  }

} //LowerorEqualboundImpl
