/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.sml.sml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.sml.sml.Penalty;
import org.xtext.example.sml.sml.SmlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Penalty</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PenaltyImpl extends OccurenceImpl implements Penalty
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PenaltyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmlPackage.Literals.PENALTY;
  }

} //PenaltyImpl
