/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml.sml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.sml.sml.SmlPackage;
import org.xtext.example.sml.sml.Upperbound;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Upperbound</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UpperboundImpl extends RangeImpl implements Upperbound
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UpperboundImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmlPackage.Literals.UPPERBOUND;
  }

} //UpperboundImpl
