/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.sml.sml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.sml.sml.SmlPackage;
import org.xtext.example.sml.sml.UpperorEqualbound;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Upperor Equalbound</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UpperorEqualboundImpl extends RangeImpl implements UpperorEqualbound
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UpperorEqualboundImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmlPackage.Literals.UPPEROR_EQUALBOUND;
  }

} //UpperorEqualboundImpl
