/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.sml.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.sml.ui.internal.SmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SmlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SmlActivator activator = SmlActivator.getInstance();
		return activator != null ? activator.getInjector(SmlActivator.ORG_XTEXT_EXAMPLE_SML_SML) : null;
	}

}
